export const CHANGE_NAME_CONSENT = 'CHANGE_NAME_CONSENT';
export const CHANGE_EMAIL_CONSENT = 'CHANGE_EMAIL_CONSENT';
export const CHANGE_AGREEMENTS_CONSENT = 'CHANGE_AGREEMENTS_CONSENT';
export const CREATE_CONSENT_STARTED = 'CREATE_CONSENT_STARTED';
export const CREATE_CONSENT_FAILED = 'CREATE_CONSENT_FAILED';
export const CREATE_CONSENT_FINISHED = 'CREATE_CONSENT_FINISHED';
